### PR TITLE
**Fix:** TopBarSelect types are broken

### PR DESCRIPTION
**Pull request by march213**
# Summary
Fixes https://github.com/contiamo/operational-ui/issues/1099
Change type signature for `TopbarSelect`.
Change the provided function parameter type from `string` to `IContextMenuItem`.

# Related issue

https://github.com/contiamo/operational-ui/issues/1099

# To be tested

Me
- [x] No error or warning in the console on `localhost:6060`
- [x] No TS errors

Tester 1

- [ ] Things look good on the demo.
- [ ] Should not be any TS errors
  

Tester 2

- [ ] Things look good on the demo.
- [ ] Should not be any TS errors

### CODE REVIEW

**Comment by stereobooster** [comment]
@march213 can you please fix example in the playground as well?

Screenshot 2019-07-01 at 17 44 22

**Comment by march213** [comment]
I fixed following examples:
- `Topbar/README.md`
- `TopbarSelect/README.md`

**Comment by stereobooster** [comment]
Screenshot 2019-07-02 at 10 06 34

If you will go to online playground you will see that there is TS error. TS complains that value can string and object, but we handle only object case.

**Comment by march213** [comment]
Yeah, I was checking online playground locally, making sure it is working ... And didn’t notice any ts errors 🤔
I’ll fix it

**Comment by march213** [comment]
I'm a little bit confusing.
I'm not sure how to fix it, sorry. 😢

The following code fix that problem:
```ts
const [activeDisplay, setActiveDisplay] = React.useState(undefined)
```

But if you would set the default parameter to a `string`, you'll get an error.

**Comment by TejasQ** [comment]
I think as a first iteration, coercing `item` to a string in the README example, so it becomes

```js
onChange={item => setActiveDisplay(String(item.label))}
```

will be enough to get this merged. At a later stage, we might want to think about improving the interfaces of ContextMenu and components that use it to harness the power of generics to dictate what their items and their labels are. This, I think is a bigger topic. Let's open an issue for it.

Not sure how deep your TypeScript interest is, @march213, but that could be fun if you want to take it on separate to this PR.

**Comment by stereobooster** [comment]
@TejasQ proposed solution here https://github.com/contiamo/operational-ui/issues/1099#issuecomment-506776580

**Comment by march213** [comment]
@stereobooster Yeah, when I tried this one `onChange={item => typeof item.label === "string" && setActiveDisplay(item.label)}` it was based on the proposed solution. But if I move typeof checking to a function, it stop working 😥

image

**Comment by march213** [comment]
@TejasQ My Typescript interest is very high, because I see the benefits of using it and I really want to learn it properly.

**Comment by march213** [comment]
I used this one for fix:
```ts
onChange={item => setActiveDisplay(String(item.label))}
```

**Pull request merged**
