### PR TITLE
Update sidebar.

### PR DESCRIPTION
**Pull request by ImogenF**
- No coloured border next to expanded items in sidenav - replaced with light grey background.

### CODE REVIEW

**Comment by TejasQ** [comment]
@micha-f [What do you think?](https://deploy-preview-552--operational-ui.netlify.com/#!/sidenav)

**Comment by micha-f** [comment]
Can we remove the grey background for expanded items? I think it looks better all white.

**Comment by TejasQ** [comment]
[Remove colored border from sidenav](https://trello.com/c/7Py74B9q/226-remove-colored-border-from-sidenav)

**Comment by TejasQ** [comment]
@micha-f one more look plz

**Comment by micha-f** [comment]
@ImogenF beautiful 👍

**Comment by micha-f** [comment]
@peterszerzo What do you prefer? It actually looks good to me without the hover background. The caret is a good indicator that you can click the collapsed group.

**Comment by peterszerzo** [comment]
@micha-f you're totally right, I was looking at one that didn't display the caret and forgot about it :)

**Pull request merged**
