### PR TITLE
**Fix:** width auto, for some reason, collapses width of textarea inside of it

### PR DESCRIPTION
**Pull request by stereobooster**
# Summary

before:
screenshot 2019-03-01 at 14 43 54

after:
screenshot 2019-03-01 at 14 44 13

# Related issue

N/A

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by mpotomin** [comment]
There are some unexpected regressions/changes to `Input`s and other side effects by this PR. @TejasQ should have already fixed this in #922? 

screenshot 2019-03-01 at 16 13 07 2

**Comment by stereobooster** [comment]
I wouldn't call it unwanted behaviour. Initial problem which I tried to solve is that textareas and inputs have different width. See screenshot before. And after all inputs and textareas have the same width (except size modifiers, like fullwidth)

**Comment by TejasQ** [comment]
@stereobooster let's base this pull request on #922

**Comment by TejasQ** [comment]
@stereobooster would you like to:

a) rebase this on #922 
b) fix this directly in #922 

?

**Comment by TejasQ** [comment]
I suggest we close this in favor of #922

**Pull request closed without merging**
