### PR TITLE
**Fix:** Select in Modal

### LINKED ISSUE #1240: Can't use <Select /> within a Modal
Using `<Select />` inside the <Modal /> renders the Listbox behind the Modal:

Screenshot 2019-09-26 at 14 48 59

### PR DESCRIPTION
**Pull request by TejasQ**
# Summary
This PR fixes #1240.

# Related issue
#1240

# To be tested

Me
- [x] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by stereobooster** [comment]
@TejasQ can you please add example for `<Modal />` component?

**Comment by stereobooster** [comment]
@TejasQ I pushed one commit with example in modal feel free to force push if you have local changes

**Comment by stereobooster** [comment]
Screenshot 2019-09-26 at 16 16 52

**Comment by TejasQ** [comment]
@stereobooster – looks good. Shall we merge?

**Pull request merged**
