### PR TITLE
  **Fix:** adjust buttons in tabs

### PR DESCRIPTION
**Pull request by stereobooster**
# Summary

Screenshot 2019-08-08 at 11 53 51
Screenshot 2019-08-08 at 11 53 58

Screenshot 2019-08-08 at 16 52 42

# Related issue

UI-122, UI-113,  UI-120

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by fabien0102** [comment]
I tried to navigate with my keyboard, it's really hard, we can't see the focused element

image

**Comment by stereobooster** [comment]
@fabien0102 behaviour of focus isn't changed in this PR. Check master it behaves the same. Scope of the PR is to implement new design. We can open other ticket to make focus state obvious.

**Comment by fabien0102** [comment]
Fair enough, I can't test it anymore (the arrows events are stole by styleguidist ^^)

**Comment by stereobooster** [comment]
I fixed buttons here https://deploy-preview-1184--operational-ui.netlify.com/

**Pull request merged**
