### PR TITLE
**Breaking:** Update ContextMenu

### PR DESCRIPTION
**Pull request by TejasQ**
# Summary
This PR:

- updates the look of ContextMenu
- adds a `separator` property to `IContextMenuItem` that allows `"top"`, `"bottom"`, or `"both"`, allowing users to compose separators according to their requirements.
- breaks the API removing the possibility to have `string` as menu items
  - we don't really use this and it was only left in the codebase to preserve backwards compatibility, but since we're "breaking" the design with a new look, we can break it properly. 😋 

# To be tested

Me
- [x] No new error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
- [x] No regression on `ActionMenu`
- [x] No regression on `ContextMenu`
- [x] No regression on `DropdownButton`
- [x] No regression on `Select`
- [x] No regression on `TopbarSelect`
- [x] No regression on `DataTableSelect`
- [ ] No regression on `Autocomplete`

  

Tester 2

- [ ] Things look good on the demo.
- [ ] No regression on `ActionMenu`
- [ ] No regression on `ContextMenu`
- [ ] No regression on `DropdownButton`
- [ ] No regression on `Select`
- [ ] No regression on `TopbarSelect`
- [ ] No regression on `DataTableSelect`
- [ ] No regression on `Autocomplete`

### CODE REVIEW

**Comment by mpotomin** [comment]
@TejasQ  when navigating the context menu with arrows up and down, the separator the selection cursor dwells on a separator for an iteration instead of jumping to the next available item. Is it an expected behaviour? 

00-ContextMenu

**Comment by fabien0102** [comment]
I don't find any screens, everything looks bold but I can check if it's wanted or not 😕

**Comment by fabien0102** [comment]
image

But I don't think we should apply bold here for example, this looks messy

**Comment by fabien0102** [comment]
image

The grey is very light, I'm really afraid about contrast here 😕

**Comment by TejasQ** [comment]
@mpotomin, great catch! I'll look into skipping the separator.

@fabien0102 – this is the design specification from @kemal-contiamo and @micha-f . I propose we merge these and continue iterating – especially the concern about contrast. I discussed this with @micha-f and it's the same as Google Drive. I don't really think this is a problem because the contrast between the _foreground text_ and the _background color_ is still favorable. Also, people will know what is hovered/focused because it is screenreader accessible. Brief, there's no real drawback to the contrast the way it is.

Further, There is no real spec for `DropdownButton` or even use case for it now if I understand correctly since we removed the button from the product. Maybe we should remove it from Operational?

**Comment by TejasQ** [comment]
@mpotomin updated the keyboard navigability.

**Comment by micha-f** [comment]
@TejasQ Looks good.

We still need the dropdown button (albeit with slightly different styling) and it should show a dropdown that is or is styled like a context menu.

**Comment by kemal-contiamo** [comment]
> image
> 
> But I don't think we should apply bold here for example, this looks messy

It shouldn't apply bold this much indeed @fabien0102 , as the screen for this one looks like this originally: 
Screenshot 2019-07-30 at 21 33 20

**Comment by micha-f** [comment]
@kemal-contiamo But we are not using that screen anymore?

**Comment by micha-f** [comment]
@kemal-contiamo @TejasQ could this not be the new style of the DropdownButton?

image

**Comment by kemal-contiamo** [comment]
> @kemal-contiamo But we are not using the screens you posted anymore?

@micha-f yes that is the previous screens indeed. But, last week in product JF, we agreed to use the existing dropdown style for at least until the demo right? I will create a new story to update all the dropdown button style to match the new ones after the demo. At least as I understood it, this review is for tomorrow the changes to be used in the demo.

**Comment by TejasQ** [comment]
Let's deal with the DropdownButton separately – this PR is about ContextMenu. The bold text in the DropdownButton example is a concern of userland – it's code from the README to illustrate that you can put _whatever you want_ inside a ContextMenu's label – including ugly bold children.

For this reason, I don't think [this comment](https://github.com/contiamo/operational-ui/pull/1169#issuecomment-516483920) is relevant to this PR.

**Comment by mpotomin** [comment]
There is a regression in the `Autocomplete` - the new one opens empty in the example

Screenshot 2019-07-31 at 12 00 07
Screenshot 2019-07-31 at 12 00 12

**Comment by TejasQ** [comment]
That's awesome, @mpotomin! Thanks for your help!

**Comment by fabien0102** [comment]
image

**Pull request merged**
