### PR TITLE
Sidenav gradient

### PR DESCRIPTION
**Pull request by peterszerzo**
screen shot 2018-05-07 at 11 33 46 am

How does it look?

### CODE REVIEW

**Comment by micha-f** [comment]
Sexy :)

**Comment by TejasQ** [comment]
I severely dislike it because, to me, it looks like Windows 98. Can we make it more subtle?

**Comment by peterszerzo** [comment]
I agree, @TejasQ, I'll take care of it!

**Comment by peterszerzo** [comment]
This is the new version, I think it looks sufficiently subtle enough to remove Windows associations :)

screen shot 2018-05-09 at 8 14 14 am

**Comment by TejasQ** [comment]
Can we have it point bottom-right to top-left in a 45º angle?

**Comment by peterszerzo** [comment]
Agreed, looks better :)

image

**Comment by TejasQ** [comment]
Incredible.

**Pull request merged**
