### PR TITLE
feat(CON-3973): Add icons for org management

### PR DESCRIPTION
**Pull request by vijayprwyd**
# Summary

Implemented following icons :

* Active directory group
* Active directory user icon
* Organization group icon
* Project group icon
* Organization group label
* Project group label

https://contiamo.atlassian.net/browse/CON-3973

image

image

# Related issue

# To be tested

Me
- [x] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Review by brunellaa — CHANGES_REQUESTED** [review]
The code looks fine, but I'm noticing size differences between them, not sure if this creates disparity when used, but it looks a little off in the Component library.

Might want to recheck the viewBox attribute

image

**Comment by vijayprwyd** [comment]
> The code looks fine, but I'm noticing size differences between them, not sure if this creates disparity when used, but it looks a little off in the Component library.
> 
> Might want to recheck the viewBox attribute
> 
> image

Yes noticed the same , apart from view box also noticed that the `path` tag does not inherit the width of parent which is causing the issue . eg: If svg has width of `32`px  the `path` just occupies about `24`px . Need to re-validate and make some edits on the svg icon.

**Review by LucasRoesler — COMMENTED** [review]
LGTM :shipit:

**Review by brunellaa — APPROVED** [review]
The Icons look consistent now. Approved!

**Pull request merged**
