### PR TITLE
**Feature:** Support tooltips for Tree

### PR DESCRIPTION
**Pull request by stereobooster**
# Summary

Screenshot 2019-12-19 at 11 40 42

# Related issue

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by stereobooster** [comment]
It's not clicking through it's event bubbling, I can catch it and prevent propagation

**Comment by mpotomin** [comment]
@fabien0102 @stereobooster Folks, why was it merged without fixing bubbling, mentioned above?

**Comment by fabien0102** [comment]
image

@mpotomin Was fixed for me

**Comment by fabien0102** [comment]
But I may tested the wrong thing…

**Pull request merged**
