### PR TITLE
Replace xAttribute/yAttribute with series datum accessors.

### PR DESCRIPTION
**Pull request by ImogenF**
**Previously**

Series objects had `xAttribute` and `yAttribute` properties to identify how to access `x` and `y` properties from series data. 

These could not be included in the regular series accessors, because they need a different format:

- series accessor: `(series) => series.property`
- datum accessor: `(datum) => datum.property` (or `(series, datum) => datum.property`)

It also did not make sense to include them in the renderer accessors, because they are needed on a series level to calculate stacks, for instance.

**Now**

Each series object can have a `datumAccessors` property which can have `x` and `y` datum accessors. For example:

```
series: [
  {
    data: [
      { date: new Date(2018, 2, 10), profit: Math.floor(Math.random() * 500) },
      { date: new Date(2018, 2, 11), profit: Math.floor(Math.random() * 500 },
      ...
    ],
    datumAccessors: {
      x: (d) => d.date,
      y: (d) => d.profit,
    },
    key: "series1",
    renderAs: [LineRenderer],
  }
]
```

### CODE REVIEW

**Comment by ImogenF** [comment]
[Charts - x and y accessors](https://trello.com/c/h0Q0dGCG/190-charts-x-and-y-accessors)

**Comment by micha-f** [comment]
Looks good to me!

**Comment by ImogenF** [comment]
@micha-f can you click approve on this please so I can merge?

**Comment by ImogenF** [comment]
Ugh, and @peterszerzo please too. Rebasing removed the approvals.

**Pull request merged**
