### PR TITLE
**Feature:** Support arrays in DataTable

### PR DESCRIPTION
**Pull request by stereobooster**
# Summary

Support arrays in DataTable

With `String()`:
Screenshot 2020-04-21 at 10 27 15

With `JSON.stringify`:
Screenshot 2020-04-21 at 10 27 15

Or I can implement custom "stringifier"?

# Related issue

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by stereobooster** [comment]
@mpotomin WDYT?

**Comment by mpotomin** [comment]
> @mpotomin WDYT?

Could you elaborate what exactly are asking for?

**Comment by stereobooster** [comment]
I'm sorry. I implemented support for arrays with `String()` (see first screenshot, it doesn't work for `[null,null]`). I also can use `JSON.stringify` (second screenshot), or I can implement something else. What your thoughts on that

**Comment by mpotomin** [comment]
> I'm sorry. I implemented support for arrays with `String()` (see first screenshot, it doesn't work for `[null,null]`). I also can use `JSON.stringify` (second screenshot), or I can implement something else. What your thoughts on that

using `JSON.stringify` sounds like a good idea, since it will take care of the issue with `null`
Screenshot 2020-04-21 at 11 05 36

@stereobooster What would be the advantage of using a custom "stringifier"?

**Comment by stereobooster** [comment]
> What would be the advantage of using a custom "stringifier"?

Some kind of custom behaviour, if we need one

**Comment by mpotomin** [comment]
> > What would be the advantage of using a custom "stringifier"?
> 
> Some kind of custom behaviour, if we need one

Do we need one now? If not, `JSON.stringify` could be good enough

**Comment by stereobooster** [comment]
JSON stringify can throw Exceptions, we probably don't need to worry about it...

> Throws a TypeError ("cyclic object value") exception when a circular reference is found.
> Throws a TypeError ("BigInt value can't be serialized in JSON") when trying to stringify a BigInt value.

**Comment by micha-f** [comment]
JSON.stringify looks good

**Pull request merged**
