### PR TITLE
Avatar and nametag color palette

### PR DESCRIPTION
**Pull request by peterszerzo**
This PR adds new color palettes for avatars and visualizations, like so:

screen shot 2018-07-06 at 2 42 41 pm

I wrote up some thoughts on the selection process here: https://beta.observablehq.com/@peterszerzo/studying-visualization-color-palettes-for-contiamo.

There are 10 colors at the moment, with the assumption that we'll add some new interpolations as our needs grow depending on how this palette performs.

### CODE REVIEW

**Comment by TejasQ** [comment]
Looks great!

**Comment by micha-f** [comment]
Can we apply this color scheme to the visual tests @ImogenF so we can evaluate how it looks?

**Comment by peterszerzo** [comment]
@micha-f it's in there already, although unfortunately the visual test cases website is a little buggy :/: https://deploy-preview-559--operational-ui.netlify.com/visual-tests/#charts/general-3 - unfortunately, the blue color doesn't show up first for some reason, so it's hard to have a good overview.

**Comment by micha-f** [comment]
@peterszerzo Right!
Might be interesting to add a couple of examples with more than two colors, so we can better decide on the ordering (@ImogenF ).

**Comment by peterszerzo** [comment]
@micha-f I opened an issue to implement color assignment in name tags the same way avatars do it: https://github.com/contiamo/operational-ui/issues/564. This branch is ready to merge with the avatar colors.

**Comment by peterszerzo** [comment]
@contiamo/frontend just to clarify, the scope of this PR has changed - it no longer takes care of visualization color palettes at all. Stay tuned for a different PR for that.

**Pull request merged**
