### PR TITLE
**Fix:** Accordion panel overflow.

### PR DESCRIPTION
**Pull request by ImogenF**
# Summary

Strange behaviour in the workbench sidebar datasources tree traced back to the `overflow` CSS property in the AccordionSection.

# Related issue

# To be tested

Me
- [x] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

**Comment by ImogenF** [comment]
Damn it. I hate CSS.

**Comment by stereobooster** [comment]
I'm not sure if this what the PR was about, but I would expect this

Screenshot 2019-08-14 at 15 21 13 copy

not this

Screenshot 2019-08-14 at 15 21 13

**Comment by fabien0102** [comment]
This PR #1195 should also help the behaviour of the tree inside the accordion ;) I finally implement the design specifications 😅 

image

**Comment by ImogenF** [comment]
Closed in favour of #1195

**Pull request closed without merging**
